# Generated by Django 4.2.15 on 2024-09-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
