# Generated by Django 4.2.15 on 2024-10-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_classschedule_teacherschedule_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slot_10_11',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slot_11_12',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slot_12_13',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slot_13_14',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slot_14_15',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slot_15_16',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slot_16_17',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='slot_9_10',
            field=models.CharField(choices=[('A', 'Available'), ('N', 'Not Available')], default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
